language: node_js
sudo: required
services:
- docker
script:
- make build test
deploy:
  provider: npm
  email: jenkins-reform@hmcts.net
  api_key:
    secure: qwTal1DS01u91DcusrFumWAUptdBbUeEDa360d5G4DUj0zOAP5RgHwN47LditVxhI5qpK28m36LaTYnqhXi/pogG+XAxEQppfcD3HsWGm738oB/YBZhjyG8v96/ACQQECgg+q6QyWG2dSw5TTB9Ldn/+BFLoXQDveRLf2MaFHHcyJvWqelUcus+jhVgUQbB2FdzhgCrI143oF+z2SvXD+l2DvxDu1wIks12iaJORz/P4fHJ2baZ5xBMFs668RupXk+IM7shChUaZ7skt/LiamKFemDEu0mCR0D/76RwoamxzZ0iQvIj2kP5ghSYuBMBkymbe5mgHd1tZNum0bZW10bJkf+h/FA0I1cjfiKguBkGd/lqZ0debmGfG7vJBp5mtAJUdtCXFxc4bY0plg01VrS8Zf02HDc7EGhwVQUC9xYxYOIM0cr700KCDpSXqfUBaIUHLKE8fyVEVgL1HXchhLyjR8CZRtnt1UTNmSEZP5eH3D3ajSi+z2DgTq8166VUvy0d0HgPyVKaLm2sIyzkfISQToHvirH5wyFtm87N9a1kbyOksAFLPYq4WKZ6lEXUtjA+jNG2kIBoBpQPi6Hf6DyXYc7SX485TsDAbuUz4+UsLLaeU7W49Wd9IGsjhU2DlOhCAkPnwlqnu/rY1QjBjt1ksy5gES8N6cqZgmFen250=
  on:
    tags: true
    repo: hmcts/look-and-feel
