sudo: required

services:
  - docker

script:
  - make build test

deploy:
  provider: npm
  email: jenkins-reform@hmcts.net
  api_key:
    secure: C1m46KTDlA7+mDZHv5X5+jyWlLq74YM/ajiY8Hv6QN77bn3S+14N43k0VVDPYuBkNfJoNfJ2WpzTeRRGjCsp0IvpxnaQqk69QKweiGGGRladpxYZcfu7JbDc7IfXPbh6hV0Ce2IHnTwIW1CojTw4WhuqCrlUd+x2nCUe2o5XZtSZAZIuBcuZHp2TYGqPq/sTwyM/5T7fBePDptAubkPbTg0ADyd/+63pTT8lS9HTw5+wsFYA6m99MSWej2+lNJn7YT3dzWHNR3k70yVVIZhNEVN2ZWOS3i0b7ut7fa+P5kALejsR6d91zSti0SXJM0Lk/Z24EWNkBivBAYmYq1qzroPFOrI1ahUIfiEHfb9gjpwob32gWAS1UlhWyaFdrjh7rtUmAtMHHIZqVItIz9Y1CEYjaHidqQGF0QC1cqwBN1X30V2jjZ7nWCvN5xAfJV45/VEaq2WHXasv3pDQQ8XZCv7y5GJgwBsMfOVdlWwEXXYGj+bK32v2uAX9OomqHbvGmdT+qxBbTw93u+fmrj+9yndavvJK0BecQPHPM8UmFMSBIxpMRswQ0pP1fzBUNjFKS/jlKn1QOJZCLtXtUmvan57P6E0yaiEphDFNQeGLKAU4Sn3CUGxPOhTHUNAdEkGIhX+k2tTz6GlsY3nvYcIz7gnyaSiZ9YvZSHhBpOKmRug=
  on:
    tags: true
    repo: hmcts/look-and-feel
