sudo: required

services:
  - docker

script:
  - make build test

deploy:
  provider: npm
  email: jenkins-reform@hmcts.net
  api_key:
    secure: Zy0Abiz1RVPZS5giHvkgocvrIRrATEtvsrOuC0OJ4qcnvB0HRrIopVRvMEzcxld3JnHjuBpg9IWKRl35ByHQ+LbYt6ztvpL+JaVpMvUnoX0jG0TacHUDQtsxeNVuCY7rNUFlrytvS/t9CBSrPMz1aPjtYkGqcxE8Cy7YtuEF4Q8FSD+mW5p9TOVK3OCtaSEXslHi4YfJ9PRrGKkk+3Ps1nv6yi89elQLqX+lkH7aSqr1te4SrKFDmH+tnQINkqhk5+MuY7LPr+efa3GPU0frZfEAmsgcWDFTsIwzkv/EixUFl003WATC3lWFfLiuodAfpXKzRkN1qxu10COIEBoydcay/G0UE4m3MhG4lMJacFX2/xPoMgAWr4qoEkbIGHAd/9LaRsCRYssP6UA4axvCZ3v99hkqD7YUpni63aNjKsCMe/6zfS1BNtoGUyeW96HS6SmQP11TbZgO0Ua2ud9n8fKE6xFDcOgqKq8XeNRfeXYumoxe5W0wMO+OSSBGfHNAtme1FNQOom2eqywVmAQYrQ+uiP0oARhYPEBLamg7P4StEQqMb2yuApTZrEPtUSum+C1AP7I9lfxBaEaUeZBGMKW6Z/Ed+rh6oAS7Ch64ulXFWdiYXXHNFfkjnWPVktuuhHaV1P3xalsGnuoO+GCrpDN8DCTt2eGLxCcJnQM9t10=
  on:
    tags: true
    repo: hmcts/look-and-feel
