sudo: required

services:
  - docker

script:
  - make build test

deploy:
  provider: npm
  email: ben.diggle5@gmail.com
  api_key:
    secure: IA5KKGvw6m6C0zpgyzONu72mbiNAEiV4x6Vew1ohldw/IPZzfKYegejlgOeGGtU/swAhEIAPwP3tAcGpGckKsK8zJ3seofEgw0N2me01e6KETZBBTi+e7p6AYJxyAxQmveSk9StU51TVXs9TXkxXSbPq4iN/9lUcKU5muhkBP97dGibKmM1BLvj5Y9Ql0HGtrjFdsAjz62mVCmsWV+Foyt9qsIjAliMuVvOTdaS7wVPJ2Mv9jIyHgMd28rThGL6fbvNR01TmOzVdBRSGWNcOK1Y8YPKOZK+MYgCJPzzlj5l3C9lPGJW5xveWP+nTj6ZuTs1Ni0lwIW4ZbtGWYeDojLjZOAkU71MsuY8ndiNPjWEq5dirxzr1pPOgQFbNyPLtsBz7zCra72O/bLJAK0vtuitKnzU5RfphcbxrjK+rUsaBcI2uSHpPsXZQKZ/KU6xBoS6cvmTS0yFcq1XL9g+x2extfdjqC5sy6rPGfIboJtvHllCysOmeraV0sVTmIzVW4tVdOKUEmT0FCsErjZQDbSGZwoQN12/9BphsriVMDegC3uasPVq/J+AqjQunRnO4j1K7vciG6ooKGLJJukiSShiYJA6ORBNY32PaKBLu0JJlYySVqgZIpWoLCMeFiSo5gT7DNkOw9aP6De9DFRk+TSQvT7xptShYVrihcwsXDBw=
  on:
    tags: true
    repo: hmcts/look-and-feel
