sudo: required

services:
  - docker

script:
  - make build test

deploy:
  provider: npm
  email: jenkins-reform@HMCTS.NET
  api_key:
    secure: ifuXF3jrsz/flI5w1ZKKtCrAdlFDk3h0ifo4iBBhfElAtNTx+F0gIrkP8LhTA6wtoxZVuUhasklXyfKwiMmDADKuqdhffB8/THa0hz6QZ9rrrGUlEfFW9Usavb1CHPFLh/OoewqVkQl7EdUJx5tjn+G6V/rjlQHQh+MJTc5uNgYMCQCpRVh8umJ+L132lBgLzkSAHrLRNEDqxTOhUJ6RJ8+UbtEgmKvqMlTjN2W+EGnJP1kniuK6pTszvAYbsm4eu6U/luFqfNRYvwv1N/sDIzJgK0RAEUQL709A2+k8FR/0Uo4RMrlkDB2YWoq81z1Oz28HkFsfTDUti+WDfeQkFU4WBZoyniBM7PfohqvjHOgkOR6dznuGFDvYLC3L45mGrY7wKNPFdJJ/4lifAFo+7+Is1RKz0anMF/4WSr7aLzWKps7TJ9fK8L9OYqOPEyEA0JXuOgLgN9FKiPzVLVmHHaxr9/2nZWO5WqG92Z/u1jdHV5hpHoIKdPek7TyKTsvamT0E7SKVyPzkuBncmti6hNNfqaEmAQFfbiRMzVzvqb6p/xmFaGVenlX6WbYtQs3BUcHI6NCqPhA1KpoHLd0zXVR/tSzDupUetOGkNTv11vIbK0jg3/SSm/2Qi+IDwjokOiFAlswahBtLGmEBBm4YEo0/4X9J8U6/hqJaJN2yEsI=

  on:
    tags: true
    repo: hmcts/look-and-feel
