sudo: required
services:
- docker
script:
- make build test
deploy:
  provider: npm
  email: jenkins-reform@hmcts.net
  api_key:
    secure: KnNCo8n1GmLZxDBMKsVCnTbC8QyVL0Fe/9GWUHYPGK+ibuzcQdqA+NLEADmJmogRCX01VdyMhvMpv6IBBXshzRkTT20eklSLWxoIxo4ch1mWo1GjEvFHSwYK9SZc2ZIB4tuKjRZPuLUWPHxAVqizh5rZ+pk/8p9g8NOlzl7KJhep8YrkqWiW9QmxQfRQcE9dxG6etmm3Aks72wz+K5SCzHEK/VMNFUCE7i96/z4HbxzkYqL57M66GdNhjCbRP8Fcp/+BvEky7rSOuU+A1uZW59N6GIz/j28wNTexQpoLHKSVjpB2zdr/paWtIwWZDdXEa1F+urA2Aq+IKNJFrJKPcQ5HUrLTXGd6k1esDefItvvkgja4tYQ7tXL+KmaEnj0nlS5WvYGcWkLvLsBM986oSdsAyALhJEBNYf9ZqARNPIBLFAh4Bx9RiWiamkdmJQHVgkbV+D7o0eJMCoGRxgQS4/YV7SPicmixdl9n+f01SfOD7SzIGL0n2dRi/c7QJnCUrxdC6mQj4ACmwIBkNFagE85y7Lf4o6gadlSk51YKP1ed7VK8OK7siQVmA3v0yuw/J7WWTOzKy07s93o84mHBBSxAZwvPnALV3GfZkPkK7+aqAyJ2R1/6WcNFoatHM58bkvnCxDt6Br36qYeeG3hlZ0CN8+d0EPi/uuH4ik/LI30=
  on:
    tags: true
    repo: hmcts/look-and-feel
