sudo: required

services:
  - docker

script:
  - make build test

deploy:
  provider: npm
  email: jenkins-reform@HMCTS.NET
  api_key:
    secure: "tWfWIn07jmvDTrhz+0exqu8awaN9UJNF69MmSI4Qi7ODnIUsfgJSDZN1F6dpPw6UX3gR3sgirq0HgdL6EyF9jmxT8BQEQE+odKWpg3EXhVLitYdtNzoL9KfmJ+fuik0r0Ej8hMp0kYPbuKDsr+RaMSh1VpE39XpxSYk6vyWfmgz3vtbjEMLzEJTazsNbCW2Wv9jquY/2Td7qKYWkWHPR88Le77+Zwko2ykxUUHSwuEO6clKEJhhK0UL8mjAhA9uw6VkmqsOiwNab9PEWNEL/y/z2Z02IWBkDI513tABxZuWDjgwPPCCWZi1MZLNCN935eLJ64cm9ghl73NDIpqAdzAJjYVftAPSWSE1sbrEpCiW+xE7MieQQSjCnFt6LhXNy1NQ4MJkNG6xgDQNZdK6LFk4DMd8uN0bFgWJxFjhJd1FRJLOEBjmeMps7Tqs1q8J5oHT1IwhcD+ibenDkfVptFLcOaaCOrwDqaaju1VjH5URN1Lsx49Yw6B9bAvPG7qxIZPLLt2jfIpDuGArhPSe3fJwo12KoNbEgeiztmzVlWlduA0IXN7rzcfvAljZGJ9HE6t7TasyCGBS9QQtfSo2kLmF7WnutW2TxfwfHkeWPWVMqjP/stRTFuZ+R/a3h26uxT0LHq+i8GxSXyLjfY9Q/qeR8Kx53PYwdtL7FJSzBYbc="

  on:
    tags: true
    repo: hmcts/look-and-feel
